"""
Pipeline 2: Video Factory
=========================
Reads today's prompt batch (generated by Pipeline 1) and calls
the Veo3 Lite API to generate MP4 videos. Saves them to output/videos/
for upload as GitHub Release assets.

Cost: ~$0.24 per 8-second clip (Veo3 Lite 720p via Gemini API)
Runs: 2pm EAT daily via GitHub Actions cron
Control spend: set MAX_VIDEOS env var (default 3 = ~$0.72/day)
"""
import os
import json
import time
import requests
from datetime import date
from pathlib import Path

TODAY = date.today().isoformat()
os.environ["TODAY"] = TODAY

PROMPT_FILE = Path(f"data/prompts/{TODAY}.json")
OUTPUT_DIR = Path("output/videos")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

MAX_VIDEOS = int(os.getenv("MAX_VIDEOS", "3"))
GOOGLE_API_KEY = os.environ["GOOGLE_API_KEY"]

print(f"Video Factory — {TODAY}")
print(f"Max videos: {MAX_VIDEOS} (~${MAX_VIDEOS * 0.24:.2f} estimated cost)")

if not PROMPT_FILE.exists():
    print(f"ERROR: No prompt file found at {PROMPT_FILE}")
    print("Pipeline 1 must run first. Trigger it manually or wait for its cron.")
    exit(1)

with open(PROMPT_FILE) as f:
    data = json.load(f)

prompts = data["prompts"][:MAX_VIDEOS]
print(f"Loaded {len(data['prompts'])} prompts, generating {len(prompts)}")

# ─── Veo3 generation via Gemini API ──────────────────────────────────────────

def generate_video_veo3(prompt_text: str, output_path: Path) -> bool:
    """
    Submit a Veo3 Lite generation job and poll until complete.
    Downloads the resulting MP4 to output_path.
    Returns True on success, False on failure.
    """
    API_BASE = "https://generativelanguage.googleapis.com/v1beta"

    # Step 1: Submit generation job
    submit_url = f"{API_BASE}/models/veo-3.1-lite-generate-preview:predictLongRunning"
    headers = {
        "Content-Type": "application/json",
        "x-goog-api-key": GOOGLE_API_KEY,
    }
    payload = {
        "instances": [{"prompt": prompt_text}],
        "parameters": {
            "aspectRatio": "9:16",
            "durationSeconds": 8,
            "numberOfVideos": 1,
            "personGeneration": "dont_allow",
            "addWatermark": False,
        },
    }

    print(f"  Submitting to Veo3 Lite...")
    try:
        resp = requests.post(submit_url, json=payload, headers=headers, timeout=60)
        resp.raise_for_status()
        operation = resp.json()
        operation_name = operation.get("name", "")
        if not operation_name:
            print(f"  ERROR: No operation name in response: {operation}")
            return False
    except Exception as e:
        print(f"  Submit failed: {e}")
        if hasattr(e, 'response') and e.response is not None:
            print(f"  Response: {e.response.text[:300]}")
        return False

    # Step 2: Poll for completion
    poll_url = f"{API_BASE}/{operation_name}"
    print(f"  Polling operation {operation_name.split('/')[-1]}...", end="", flush=True)

    max_polls = 60  # 10 minutes max
    for attempt in range(max_polls):
        time.sleep(10)
        try:
            poll_resp = requests.get(
                poll_url,
                headers={"x-goog-api-key": GOOGLE_API_KEY},
                timeout=30,
            )
            poll_resp.raise_for_status()
            status = poll_resp.json()
        except Exception as e:
            print(f"\n  Poll error: {e}")
            continue

        if status.get("done"):
            print(" done")
            response_data = status.get("response", {})
            predictions = response_data.get("predictions", [])
            if not predictions:
                print(f"  ERROR: No predictions in response")
                return False

            video_uri = predictions[0].get("bytesBase64Encoded") or predictions[0].get("videoUri", "")

            # Handle base64-encoded video
            if predictions[0].get("bytesBase64Encoded"):
                import base64
                video_bytes = base64.b64decode(predictions[0]["bytesBase64Encoded"])
                with open(output_path, "wb") as f:
                    f.write(video_bytes)
                print(f"  Saved {len(video_bytes)/1024/1024:.1f} MB (base64)")
                return True

            # Handle URI download
            elif video_uri:
                print(f"  Downloading video...")
                dl_resp = requests.get(
                    video_uri,
                    headers={"x-goog-api-key": GOOGLE_API_KEY},
                    stream=True,
                    timeout=120,
                )
                with open(output_path, "wb") as f:
                    for chunk in dl_resp.iter_content(chunk_size=8192):
                        f.write(chunk)
                size_mb = output_path.stat().st_size / 1024 / 1024
                print(f"  Saved {size_mb:.1f} MB")
                return True
            else:
                print(f"  ERROR: No video data in response: {predictions[0].keys()}")
                return False
        else:
            print(".", end="", flush=True)

    print(f"\n  TIMEOUT after {max_polls * 10}s")
    return False


# ─── Main generation loop ─────────────────────────────────────────────────────

results = []

for i, pkg in enumerate(prompts):
    animal = pkg["animal"]
    veo_prompt = pkg["veo3_prompt"]
    caption = pkg["caption"]
    slug = animal.lower().replace(" ", "_").replace("-", "_")

    print(f"\n[{i+1}/{len(prompts)}] {animal}")
    print(f"  Caption: {caption}")

    output_path = OUTPUT_DIR / f"{TODAY}_{slug}_{i+1:02d}.mp4"

    # Skip if already generated (re-run safety)
    if output_path.exists() and output_path.stat().st_size > 10000:
        print(f"  Already exists, skipping: {output_path.name}")
        results.append({
            "index": i,
            "animal": animal,
            "file": str(output_path),
            "filename": output_path.name,
            "caption": caption,
            "caption_alt": pkg.get("caption_alt", ""),
            "hook_seconds": pkg.get("hook_seconds", ""),
            "status": "skipped",
        })
        continue

    success = generate_video_veo3(veo_prompt, output_path)

    results.append({
        "index": i,
        "animal": animal,
        "file": str(output_path),
        "filename": output_path.name,
        "caption": caption,
        "caption_alt": pkg.get("caption_alt", ""),
        "hook_seconds": pkg.get("hook_seconds", ""),
        "status": "success" if success else "failed",
    })

    if not success:
        print(f"  Skipping download, continuing to next...")

    time.sleep(3)

# ─── Save manifest for Pipeline 3 ────────────────────────────────────────────

manifest_path = OUTPUT_DIR / f"{TODAY}_manifest.json"
manifest = {
    "date": TODAY,
    "generated": len([r for r in results if r["status"] == "success"]),
    "failed": len([r for r in results if r["status"] == "failed"]),
    "videos": results,
}

with open(manifest_path, "w") as f:
    json.dump(manifest, f, indent=2)

success_count = manifest["generated"]
print(f"\n{'='*50}")
print(f"Done: {success_count}/{len(results)} videos generated")
print(f"Manifest: {manifest_path}")
if success_count > 0:
    print(f"Files ready for GitHub Release upload.")
